"""add MatchStats and UserMatchStats

Revision ID: 69f5f4670299
Revises: 
Create Date: 2025-05-03 21:14:44.680564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f5f4670299'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('match_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'match_ids')
    # ### end Alembic commands ###
