"""Добавил каскадноре удаление заявок при удалении юзера

Revision ID: 9b4c196675e4
Revises: 69f5f4670299
Create Date: 2025-06-02 10:25:18.997459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4c196675e4'
down_revision = '69f5f4670299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'pubg_match_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('pubg_match_id', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
